services:
  golang_api:
    container_name: golang_api
    build:
      context: ./backend
    volumes:
      - ./sharing:/data # accessable dir
    expose:
      - "8080"  # internal docker only
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro # Nginx basic auth
    ports:
      - "80:80"  # open to host
    depends_on:
      - golang_api
    restart: unless-stopped
